name: myenv
#dependencies:
#  - cudatoolkit=11.6.0
#  - python=3.10.4
#  - pytorch
#  - pytorch=2.0.1
#  - pytorch-cuda=11.7
#  - numpy==1.22.4

channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pip
  - pip:
      - einops
